//
// Generated file, do not edit! Created by nedtool 5.6 from TimeResponse.msg.
//

#ifndef __TIMERESPONSE_M_H
#define __TIMERESPONSE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>TimeResponse.msg:1</tt> by nedtool.
 * <pre>
 * message TimeResponse
 * {
 *     double nodeIdTime[2];
 * }
 * </pre>
 */
class TimeResponse : public ::omnetpp::cMessage
{
  protected:
    double nodeIdTime[2];

  private:
    void copy(const TimeResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TimeResponse&);

  public:
    TimeResponse(const char *name=nullptr, short kind=0);
    TimeResponse(const TimeResponse& other);
    virtual ~TimeResponse();
    TimeResponse& operator=(const TimeResponse& other);
    virtual TimeResponse *dup() const override {return new TimeResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getNodeIdTimeArraySize() const;
    virtual double getNodeIdTime(unsigned int k) const;
    virtual void setNodeIdTime(unsigned int k, double nodeIdTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TimeResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TimeResponse& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TIMERESPONSE_M_H

